# Generated by Django 4.1.3 on 2022-11-25 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='quizoptionanswer',
            name='quiz_answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_option_answers', to='course.quizanswer'),
        ),
        migrations.AddField(
            model_name='quizoptionanswer',
            name='quiz_option',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_option_answer', to='course.quizoption'),
        ),
        migrations.AddField(
            model_name='quizoption',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='course.quiz'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='course.quiz'),
        ),
        migrations.AddField(
            model_name='quizanswer',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_answers', to='course.subscription'),
        ),
        migrations.AddField(
            model_name='quiz',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='course.course'),
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, through='course.Subscription', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='subscription',
            unique_together={('student', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='quizoptionanswer',
            unique_together={('quiz_answer', 'quiz_option')},
        ),
        migrations.AlterUniqueTogether(
            name='quizanswer',
            unique_together={('subscription', 'quiz')},
        ),
    ]
