# Generated by Django 4.1.3 on 2022-11-18 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_quiz_quizoption'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name_plural': 'quizes'},
        ),
        migrations.AlterField(
            model_name='quizoption',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
