# Generated by Django 4.1.3 on 2022-11-18 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0003_alter_quiz_options_alter_quizoption_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizoption',
            name='order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
