# Generated by Django 4.1.3 on 2022-11-24 12:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0006_alter_course_students'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
        migrations.AddField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, through='course.Subscription', to=settings.AUTH_USER_MODEL),
        ),
    ]
