# Generated by Django 4.1.3 on 2022-11-24 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0007_remove_course_students_course_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizanswer',
            name='succeeded',
            field=models.BooleanField(default=False),
        ),
    ]
